language: php

php:
  - 8.0.1
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

install:
  - composer update -n --prefer-dist

script:
  - mkdir -p build/logs
  - XDEBUG_MODE=coverage php vendor/bin/phpunit -c phpunit.xml.dist
  - vendor/bin/psalm --no-cache

after_success:
  - travis_retry php vendor/bin/php-coveralls