language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly
  fast_finish: true

cache:
  directories:
    - $HOME/.php-cs-fixer

install:
  - composer update -n --prefer-dist

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - vendor/bin/php-cs-fixer fix --config=.php_cs.dist --verbose --diff --dry-run

after_success:
  - travis_retry php vendor/bin/php-coveralls