language: php

php:
  - 7.4
  - 8.0
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

cache:
  directories:
    - $HOME/.php-cs-fixer

install:
  - composer update -n --prefer-dist

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - vendor/bin/psalm --no-cache

after_success:
  - travis_retry php vendor/bin/php-coveralls