language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly
  fast_finish: true

install:
  - composer update -n --prefer-dist
